//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniDbTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConsumer
    {
        public int ConsumerID { get; set; }
        public int GroupID { get; set; }
        public string LN { get; set; }
        public string FN { get; set; }
        public string MI { get; set; }
        public string LNSoundex { get; set; }
        public string MlAddr1 { get; set; }
        public string C_MlAddr2 { get; set; }
        public string MlCity { get; set; }
        public string MlState { get; set; }
        public string MlZip { get; set; }
        public string AcTel { get; set; }
        public string Tel { get; set; }
        public Nullable<int> RaceID { get; set; }
        public string C_SSN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> bChildren { get; set; }
        public Nullable<byte> NumChildren { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<byte> bFamilyIns { get; set; }
        public Nullable<byte> C_bIns { get; set; }
        public Nullable<byte> bHasDr { get; set; }
        public string DrName { get; set; }
        public string DrLocCit { get; set; }
        public string DrLocSt { get; set; }
        public string Gender { get; set; }
        public Nullable<int> EmploymentStatusID { get; set; }
        public Nullable<byte> bFamHisCancer { get; set; }
        public Nullable<byte> bFamHisHd { get; set; }
        public Nullable<byte> bFamHisDiabetes { get; set; }
        public string InsCarrier { get; set; }
        public Nullable<byte> bFailedValidateAddr { get; set; }
        public string NAGroupName { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> LastModDt { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string Suffix { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public string GeoResult { get; set; }
        public string Email { get; set; }
        public Nullable<int> InsProviderID { get; set; }
        public Nullable<int> YoungestChildYOB { get; set; }
        public Nullable<byte> bFamHisHighBldPrs { get; set; }
        public Nullable<byte> bFamHisOsteo { get; set; }
        public Nullable<byte> bFamHisStroke { get; set; }
        public string PreferredHospital { get; set; }
        public Nullable<int> InsCarrierTypeID { get; set; }
        public Nullable<byte> bDoNotMarketTo { get; set; }
        public string ssnlastfour { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string Custom7 { get; set; }
        public string Custom8 { get; set; }
        public string Custom9 { get; set; }
        public string Custom10 { get; set; }
        public string mailcarrt { get; set; }
        public string mailerrorcodes { get; set; }
        public string maillotnum { get; set; }
        public string maildpc { get; set; }
        public string mailpresortid { get; set; }
        public string mailtrayid { get; set; }
        public string mailpackageid { get; set; }
        public string mailendorsementline { get; set; }
        public string maildpbarcode { get; set; }
        public string mailws { get; set; }
        public string tempid { get; set; }
        public Nullable<System.DateTime> LastPHRMailDt { get; set; }
    }
}
